// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsw68z9iWwI3j5D2CRT3eqiIojba7u1e8',
    appId: '1:59234127013:web:928dfeb85b6d7246ab514c',
    messagingSenderId: '59234127013',
    projectId: 'biosync-mobile',
    authDomain: 'biosync-mobile.firebaseapp.com',
    storageBucket: 'biosync-mobile.firebasestorage.app',
    measurementId: 'G-K7XXEDHR10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJc7wpsP21u4Xa-mtFRlz50t4B3a-0Lsg',
    appId: '1:59234127013:android:ebccf7729cb60e80ab514c',
    messagingSenderId: '59234127013',
    projectId: 'biosync-mobile',
    storageBucket: 'biosync-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKDaMvvvu1-1DeiV0ttAx83I8bwxLsUzg',
    appId: '1:59234127013:ios:94c3ee6aeb3fd021ab514c',
    messagingSenderId: '59234127013',
    projectId: 'biosync-mobile',
    storageBucket: 'biosync-mobile.firebasestorage.app',
    iosBundleId: 'com.example.biosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKDaMvvvu1-1DeiV0ttAx83I8bwxLsUzg',
    appId: '1:59234127013:ios:94c3ee6aeb3fd021ab514c',
    messagingSenderId: '59234127013',
    projectId: 'biosync-mobile',
    storageBucket: 'biosync-mobile.firebasestorage.app',
    iosBundleId: 'com.example.biosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsw68z9iWwI3j5D2CRT3eqiIojba7u1e8',
    appId: '1:59234127013:web:39281f03f269ee75ab514c',
    messagingSenderId: '59234127013',
    projectId: 'biosync-mobile',
    authDomain: 'biosync-mobile.firebaseapp.com',
    storageBucket: 'biosync-mobile.firebasestorage.app',
    measurementId: 'G-0ZT3YHCFPX',
  );

}